### PR TITLE
Added 'a', the simple alarm to Python.

### PR DESCRIPTION
**Pull request by doczi-dominik**
Added 'a' (https://github.com/doczi-dominik/a), the simple CLI Linux alarm to the Python category. Heavily-commented, designed for beginners to expand upon.

No issues yet, although the repo has the 'first-timers-only' topic, and the repo includes a 'Challenges.md' file, which contains easy modifications for beginners to get started.

### CODE REVIEW

**Comment by doczi-dominik** [comment]
Alright, added (label: good first issue) to the title and included the appropriate link.

**Comment by doczi-dominik** [comment]
What do you mean? The label is (label: good first issue) and the link is https://github.com/doczi-dominik/a/labels/good%20first%20issue.

**Comment by vvscode** [comment]
I'm about case

**Comment by doczi-dominik** [comment]
If you are talking about Good First Issue not being lowercase like the actual label, I just changed it. 👍

**Comment by MunGell** [comment]
Hi @doczi-dominik 

Sorry, but your repo does not have many beginner-friendly issues not contributors that could mentor new comers. I am closing this PR for now, please feel free to re-open when you will get bigger community around you project.

**Pull request closed without merging**
