### PR TITLE
Add Basic Car Maintenance iOS app

### PR DESCRIPTION
**Pull request by mikaelacaron**
Adding my iOS app called "Basic Car Maintenance" it's open  source for Hacktoberfest and beyond

### CODE REVIEW

**Comment by mikaelacaron** [comment]
@MunGell any updates on this? I'd love to get it merged for Hacktoberfest, especially since there's only one other Swift project

**Review by sammyhori — APPROVED** [review]
Looks good, still active repo with "good first issue" issues

**Comment by mikaelacaron** [comment]
Thank you!!

**Comment by sammyhori** [comment]
No problem, thanks for the entry, I was glad to get it finally merged after all this time.

**Pull request merged**
