### PR TITLE
Adding Time to Leave to Javascript

### PR DESCRIPTION
**Pull request by thamara**
Please complete the following checklist if your PR is adding new link to the list:

- [x] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [x] This PR does not introduce duplicates to the list
- [x] The link is added at the bottom of the list category
- [x] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [x] The link I add follows the suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

### CODE REVIEW

**Comment by thamara** [comment]
I don't see any problem here. Just waiting for review :)

**Comment by thamara** [comment]
Still waiting review.

**Comment by thamara** [comment]
I guess one untold step on getting a PR reviewed/accepted is to win over the stale bot. I must say this is **very frustrating**.

**Comment by thamara** [comment]
Ok, I honestly give up. This is the last comment I put in here.

**Comment by jtpavlock** [comment]
Wow that is an extremely aggressive stale bot

**Comment by gavv** [comment]
Agree, I like this list and am really thankful to the author, but these bot settings, with the timeout period much shorter than the typical review time on this repo, seems a bit uncivil to contributors.

**Comment by MunGell** [comment]
Hi all,

Sorry for the bot and my absence in recent months!

The bot settings are quite aggressive, but unfortunately I had to make them so after I had to go through hundreds of irrelevant PRs, especially during Hacktoberfest.

Bot is closing pull requests in 5 days, which is the number of days Hacktoberfest require you to have PR open to count it as a valuable contribution. This repository is positioned as "beginners friendly", meaning that during Hacktoberfest a lot of people create junk PRs just to get free swag. Bot prevents at least part of it...

On the topic, @thamara would you mind changing the URL to label directly, like all other links in the list?

**Comment by thamara** [comment]
Hmm, I see and understand the reasoning behind the bot, but outside Hacktoberfest this becomes really annoying. Nevertheless, I think the idea of this repository is great, and thanks for maintaining it. :)

Anyway, I'll do the said changes and will create a new PR for it soon.

**Comment by MunGell** [comment]
Hey @gavv @thamara,

Just FYI, I've decided to try something different - disabled the offending bot and enabled sponsorship on GitHub.
Will see if this work can be sustainable in that way.

**Comment by thamara** [comment]
Good luck on that :)
It sure is a very good repository and deserves some recognition!

**Pull request closed without merging**
