### PR TITLE
Add MindsDB repository

### PR DESCRIPTION
**Pull request by ZoranPandovski**
Add MindsDB project

Please complete the following checklist if your PR is adding new link to the list:

- [X] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [X] This PR does not introduce duplicates to the list
- [X] The link is added at the bottom of the list category
- [X] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [X] The link I add follows the suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @ZoranPandovski 

I believe the correct link should be https://github.com/mindsdb/mindsdb/labels/good%20first%20issue

It looks like there are no open issues with this label at the moment. 
From what I can see only one of the issues was opened this year.

Do you have any insights on if this repository is actively seeking for new contributors or expecting more beginner-friendly issues to be logged soon?

**Comment by ZoranPandovski** [comment]
Hello @MunGell. Yes, it actively looking for new contributors. We were working on getting everything in a stable version so we can start adding the contributions issues. That said, in the next period, we will start posting the issues.

**Comment by MunGell** [comment]
Cool, please update the link in the PR and I will merge it!

**Comment by ZoranPandovski** [comment]
Thanks @MunGell. I am not able to edit the PR or switch to the branch because after making this PR, I've removed the fork. I am not sure what is the best way to edit it now

**Comment by MunGell** [comment]
Hi @ZoranPandovski 

Would you be able to create a new PR then?

**Comment by ZoranPandovski** [comment]
Sure. Thanks @MunGell #687

**Pull request closed without merging**
