### PR TITLE
Add SimplQ

### PR DESCRIPTION
**Pull request by daltonfury42**
Hi, can we add SimplQ to the list, it's been gaining good traction recently.

> [SimplQ](https://github.com/SimplQ/simplQ-frontend/labels/You%20Can%20Do%20This) _(label: You can do this)_ <br> Free online queue manager for easy and instant crowd control. [Contributing Guidelines](https://github.com/SimplQ/simplQ-frontend#contributing)

Please complete the following checklist if your PR is adding new link to the list:

- [x] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [x] This PR does not introduce duplicates to the list
- [x] The link is added at the bottom of the list category
- [x] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [x] The link I add follows the suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

### CODE REVIEW

**Comment by Krishna0114** [comment]
Hey Can you accept pull request

**Comment by MunGell** [comment]
Hi @daltonfury42 

Would `good first issue` label be more appropriate?

**Comment by daltonfury42** [comment]
Yes, we use both. And it makes sense to use `good first issue` as I usually tag easy starter issues as `good first issue`.

**Comment by daltonfury42** [comment]
Thank you, Merry Christmas

**Pull request merged**
