### PR TITLE
Add the kinto project as awesome for beginners.

### PR DESCRIPTION
**Pull request by Natim**
A lightweight JSON storage service with synchronisation and sharing abilities.
http://kinto.readthedocs.org/

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @Natim 

Could you please resolve the conflict with #11?

Thanks!

**Comment by Natim** [comment]
Here you go.

**Comment by Natim** [comment]
Oh well not really. let me rework that.

**Comment by Natim** [comment]
Here you go.

**Comment by MunGell** [comment]
Thank you!

**Pull request merged**
