### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by abhishektripathi66**

### CODE REVIEW

**Comment by sammyhori** [comment]
Adds the PR opener's [DSA repo](https://github.com/abhishektripathi66/DSA).

As of writing this (2024-10-08) the repo has no and has never had any open issues so shouldn't be added to the list (at least in its current state).

**Comment by abhishektripathi66** [comment]
@sammyhori, There are some open issues in the Repo, Please do have a look at it.

**Comment by abhishektripathi66** [comment]
can we get this pull request merged @sammyhori

**Comment by sammyhori** [comment]
Sorry, I don't have merge permissions, will have to wait for someone who does...

**Comment by abhishektripathi66** [comment]
@PabloToPamblo  Please merge the Pull request as well.

**Comment by sammyhori** [comment]
I don't believe Pablo has permissions either.

**Comment by sammyhori** [comment]
Hi @abhishektripathi66 

I have made a fork of this repo [here](https://github.com/sammyhori/awesome-for-beginners).

I have been copying good pull requests across but I'll leave yours for a bit to give you the opportunity to open it yourself on my fork so that you can get the merged PR in your github history if that's something valuable to you.

**Comment by abhishektripathi66** [comment]
@sammyhori 

You want me to fork your repo and make a PR on that Repo? Is my understanding correct? else correct me

**Comment by abhishektripathi66** [comment]
@thommay @martint @MunGell Please merge it

**Comment by sammyhori** [comment]
You shouldn't need to fork my repository to make a PR on it, you should be able to do it from your current fork of this repository, but when you open a PR, change the base that you're merging into to my repo `sammyhori/awesome-for-beginners`

**Comment by abhishektripathi66** [comment]
@sammyhori Understood

**Comment by abhishektripathi66** [comment]
image

Looks like I'm Unable to find your base repo while opening PR

**Comment by MunGell** [comment]
@sammyhori you should now have permissions to merge, please check if it works for you

**Comment by sammyhori** [comment]
image

Hi @MunGell, I'm still getting this message so it looks like the permissions haven't worked.

**Comment by sammyhori** [comment]
Got the invitation, sorry didn't realise I had something I needed to accept, all good now :+1:, thanks a lot, I can remove my fork now.

**Pull request merged**
