### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by deecode15800**
Please complete the following checklist if your PR is adding new link to the list:

- [ ] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [ ] This PR does not introduce duplicates to the list
- [ ] The link is added at the bottom of the list category
- [ ] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [ ] The link I add follows the suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

### CODE REVIEW

**Comment by deecode15800** [comment]
this is great website

**Comment by deecode15800** [comment]
amazing

**Comment by deecode15800** [comment]
update README.md

**Comment by unnown** [comment]
Please mark as invalid and spam, this is an obvious attempt to get a free t-shirt by 'contributing' (hacktoberfest)
This will also ban the user for trying to abuse the system by doing marginal effort

**Comment by MunGell** [comment]
Thanks @unnown,

This repository is usually [badly hit](https://github.com/MunGell/awesome-for-beginners/issues?q=label%3Ainvalid+is%3Aclosed) by such PRs, will need to survive for the next 30 days or disable PRs feature here for October altogether.

**Pull request closed without merging**
