### PR TITLE
Add PrestaShop to PHP section

### PR DESCRIPTION
**Pull request by NeOMakinG**
Please complete the following checklist if your PR is adding new link to the list:

- [x] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [x] This PR does not introduce duplicates to the list
- [x] The link is added at the bottom of the list category
- [x] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [x] The link I add follows the suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Commenting to avoid it closing by your bot!

**Comment by NeOMakinG** [comment]
Hell no! Your bot is too fast about closing :(

**Comment by MunGell** [comment]
Hey, thanks for the PR and for keeping it alive!

The bot is quite aggressive - it was configured to fight Hacktoberfest spam, but it helps even now when I am not around to close spammy PRs.

Anyways, thanks for adding PrestaShop, here!

**Comment by NeOMakinG** [comment]
Thanks @MunGell

**Pull request merged**
