### PR TITLE
Add coala - an unified linting tool

### PR DESCRIPTION
**Pull request by SanketDG**
We at [coala](https://coala.io) are always striving to help newcomers get started with their first open source contribution!

P.S. we have an awesome hand-written guide at https://coala.io/newcomer, would it be okay to add that link in the description?

### CODE REVIEW

**Comment by SanketDG** [comment]
@JefMari ping.

**Comment by JefMari** [comment]
@SanketDG ping.

**Comment by SanketDG** [comment]
@JefMari haha fair enough, updated.

But in my defence, the PR was open for a really long time, so I wasn't sure you had considered pulling. :smile:

**Comment by MunGell** [comment]
Hi @SanketDG,

I didn't merge this PR as I was not sure it is a right thing to do. The link that you have provided is not a direct link to a label, which is not common in this list.

Can you please change the link to a direct one?
Also, can you please resolve merge conflicts correctly in this PR?

Thanks

**Comment by SanketDG** [comment]
> Can you please change the link to a direct one?

I have, but coala is very distributed in its functionality. For the sake of not confusing beginners, it wouldn't hurt to break one norm, I think and instead have https://coala.io/new as the link.

**Comment by SanketDG** [comment]
@JefMari @MunGell ping.

**Comment by MunGell** [comment]
Hi @SanketDG,

I understand that, could you please update the link to be `https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+user%3Acoala+label%3Adifficulty%2Fnewcomer++no%3Aassignee` then?

Thanks

**Comment by SanketDG** [comment]
@MunGell, done thanks!

**Comment by MunGell** [comment]
Thanks!

**Pull request merged**
