### PR TITLE
Add Mongoid to Ruby section

### PR DESCRIPTION
**Pull request by alexbevi**

### CODE REVIEW

**Comment by jgeales222222** [comment]
##### %<<<<< 

- [=|||||||=≈
∞8⁸1⅙ⁿ

**Review by sammyhori — COMMENTED** [review]
Active repo but they don't seem to really use any issue labels.
Don't know what went on in the conversation of this PR.

**Comment by sammyhori** [comment]
As this pull request goes against the contributing guideline of:

>  Ensure the contributed repository is actively maintained, has a supportive community, and **_issues with appropriate labels._**

I am closing this pull request. Feel free to reopen this PR if some issues with the correct label are made.

**Pull request closed without merging**
