### PR TITLE
Add ArviZ to list

### PR DESCRIPTION
**Pull request by canyon289**
Please complete the following checklist if your PR is adding new link to the list:

- [ X] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [ X] This PR does not introduce duplicates to the list
- [ X] The link is added at the bottom of the list category
- [ X] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [ ]X The link I add follows the suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @canyon289 

Thanks for the PR, would you mind updating the link to match the format of other links in the list?
I can merge it then

**Comment by canyon289** [comment]
Hey, yes I can. Will do so today. Thanks for reopening

**Comment by MunGell** [comment]
Hi @canyon289 

I meant the link itself should be pointing directly to the label, not search results...

**Comment by canyon289** [comment]
Alright third times a charm I hope

**Comment by canyon289** [comment]
A merge i guess?

**Comment by canyon289** [comment]
Thank you!

**Pull request merged**
