### PR TITLE
Add TEAMMATES under the new category: Java

### PR DESCRIPTION
**Pull request by songchoa**
The project TEAMMATES is added for beginners and the new category "Java" is created. Thank you for your consideration.

### CODE REVIEW

**Comment by MunGell** [comment]
Hey @songchoa 

Thanks for you contribution!
I cannot find "beginners" label in your repository and don't see any issues marked with anything similar.

Please take a look at other repositories in this list for examples.
Let me know if you have any questions.

**Comment by songchoa** [comment]
Hi @MunGell 
Sorry for the confusion. Under the issues tab of our repository, we use "p.low", "p.medium", and "p.high" as difficulty level indicator. "p.low" is the label that should be equivalent to "beginner". Please let me know if you have any concern. Thanks!

**Comment by wkurniawan07** [comment]
Hi @songchoa, thanks for stepping up and submitting a pull request for this!
@MunGell I'm one of the leads for the said project and I should clarify that `p.*` is a priority indicator, **not** difficulty level indicator. The easy-for-beginner issues can be found under `d.FirstTimers` label. In addition, we also have some easy-for-novice (early contributors who are not first timer) issues which can be found under `d.Contributors` label. Hope this clears up all doubts!

**Comment by MunGell** [comment]
Hi @wkurniawan07, thanks for clarification!

@songchoa could you please update your pull request in accordance with the comment above?

**Comment by songchoa** [comment]
@MunGell done, please check it out.

**Comment by MunGell** [comment]
Cool, thanks

**Pull request merged**
