### PR TITLE
Fix Electron label and move it under Javascript

### PR DESCRIPTION
**Pull request by MSandeep96**
Fixed Electron's beginner label. Initially it was under C++ but most of it is Javascript/Node.JS so moved it under Javascript.

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @MSandeep96 

Thank you for correcting the label.
I just went through Electron repository and it looks like most of PRs and issues are against code in C++.
I would leave it in C++ section for the time being unless you have arguments to move it to JavaScript section.

**Comment by MSandeep96** [comment]
Well there's a bit of both. How about adding it to both the sections?

**Comment by Rob-Rychs** [comment]
As someone new to javascript, I would appreciate it being listed under both sections because of how important it's becoming to the javascript community. The more awesome beginners we can introduce to electron the better!

**Comment by MunGell** [comment]
Hey @MSandeep96,

I've updated your PR per your suggestion and I am going to merge it now, just on the brink of 6 months since this PR was created. :)

Thanks for your contribution!

**Pull request merged**
