### PR TITLE
Added DisplayJS

### PR DESCRIPTION
**Pull request by arguiot**
Added [DisplayJS](https://display.js.org)

### CODE REVIEW

**Comment by vvscode** [comment]
Please update the link so that it contains filter by label

**Comment by arguiot** [comment]
@vvscode , I fixed it 😊

**Comment by vvscode** [comment]
and in such case your pr has incorrect label name ( you have `Beginner`, but your text says `beginner friendly` )

**Comment by arguiot** [comment]
@vvscode So, do I need to create another Label?

**Comment by vvscode** [comment]
What for?

You've added string

```
[DisplayJS](https://github.com/arguiot/DisplayJS/labels/Beginner) _(label: beginner friendly)_ <br> A simple JavaScript frontend framework.
```
regarding to link and labels in your repo it looks like correct vesion is 

```
[DisplayJS](https://github.com/arguiot/DisplayJS/labels/Beginner) _(label: Beginner)_ <br> A simple JavaScript frontend framework.
```

the only difference in `_(label: Beginner)_ `

**Comment by arguiot** [comment]
Could you then commit the change for me? I’m busy, so I can’t do it now 😊.

**Comment by vvscode** [comment]
@arguiot  are you serious?

**Comment by arguiot** [comment]
Oh, you know what, never mind I’ll do it

**Comment by arguiot** [comment]
Done ✅

**Comment by MunGell** [comment]
@vvscode, thanks for moderating this!

@arguiot there is only one issue with label "Beginner" in your repository and it is not a beginner-friendly one.

I am closing this PR for the moment. Please feel free to open another PR if you will have more issues to offer for new contributors.

**Pull request closed without merging**
