### PR TITLE
Added Hoodie Camp to the list under Javascript Category

### PR DESCRIPTION
**Pull request by aabi01**
Added Hoodie Camp to the list under Javascript Category

### CODE REVIEW

**Comment by MunGell** [comment]
Thank you! Could you please resolve the conflict so I will be able to merge this PR? :)

**Comment by aabi01** [comment]
@MunGell Can you please help me how to resolve this conflict?

**Comment by MunGell** [comment]
Hey @aabi01,

The conflict in file changes happened because I merged another PR that was editing same lines of text. Thus, git doesn't know how to merge your change with the existing code automatically. We have to help it manually with following steps in Terminal/Console:

1. Clone your fork of this repository if you don't have it locally yet.
2. Change directory to where you cloned or stored your repository fork.
3. Run `git remote add upstream https://github.com/MunGell/awesome-for-beginners.git` to add my repository as a second remote server for your local copy.
4. Now, run `git pull upstream master` - this will pull latest changes from my remote to your local copy. This command will indicate that there is a merge conflict in one of the files (README.md in our case).
5. Open your local copy in your text/code editor and resolve git conflicts (they are marked with `>>>>`, `====` and `<<<<` signs). Use this page for guidance: https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/
6. Commit merge changes as usual with appropriate commit message in it.
7. Push these changes to your remote, this will automatically update this PR.

More info could also be found here: http://dont-be-afraid-to-commit.readthedocs.io/en/latest/git/conflicts.html

**Comment by aabi01** [comment]
Hi @MunGell 
I have resolved the conflict and pushed it to my remote.

Thank you very much for guiding me through theses steps :)

**Comment by MunGell** [comment]
You are welcome!

**Pull request merged**
