### PR TITLE
Added language-legesher-python project to Python section

### PR DESCRIPTION
**Pull request by sdesani**
Please complete the following checklist if your PR is adding new link to the list:

- [x] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [x] This PR does not introduce duplicates to the list
- [x] The link is added at the bottom of the list category
- [x] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [x] The link I add follows suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

### CODE REVIEW

**Comment by sdesani** [comment]
Resolves https://github.com/legesher/language-legesher-python/issues/6

**Comment by sdesani** [comment]
@szabgab, If this PR is no longer going to be accepted or needed, can you comment and close this? If this can be added, let me know, I will rebase and update the PR.
cc: @madiedgar

**Comment by madiedgar** [comment]
Hey @sdesani 👋, I unfortunately don't have write access to this repository so I can't accept / merge in this PR. However, I do want to recognize your contribution and effort (and give you PR credit for hacktoberfest). I'll create an issue on `language-legesher-python` repo for you. 👍

**Comment by sdesani** [comment]
Hi @madiedgar, I really appreciate the gesture but it would not be necessary to create an issue on `language-legesher-python` as I had other PRs out there for hacktoberfest. I understand that you don't have write actions on this repo, I was just trying keeping you in the loop.

I just wanted to make sure if this PR still needs to be kept open/worked on/closed.

**Comment by MunGell** [comment]
Hi all,

I've reviewed the repo there, looks like you have a lot of contributors to it (65), disproportional to the number of ever-logged issues (9, all of which are marked for Hacktoberfest), only 9 ever-made pull-requests , 8 forks and 4 stars.

Looks like a lot of people have push access to this repository, maybe the team behind the project. Or maybe you recently moved project from a different repository, where all these 65 contributors were making changes.

In either way, I would suggest continue the good work, attract people to you project and re-open PR when you will get a community around it.

There is already one repository from your org in the list, which has healthier metrics, so was accepted to the list.

Thanks!

**Comment by madiedgar** [comment]
Thank you so much @MunGell for taking the time to look into our project and for your response. 

I've been working on this project on my own for a while now, and just released it to the open source world this Hacktoberfest (which has been such an incredible experience!). 

Your kind words and encouragement are greatly appreciated. Thank you again! ❤️

**Pull request closed without merging**
