### PR TITLE
Add activist to data.json

### PR DESCRIPTION
**Pull request by Vince155**
[activist](https://github.com/activist-org/activist) is a network for political action empowering individual to collaborate on issues that matter to them.

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for adding us here, @Vince155 :) If a maintainer here has any questions, myself or the community would be happy to address them 😊

**Review by sammyhori — APPROVED** [review]
Looks good to me, could also add python as a language

**Comment by andrewtavis** [comment]
Thanks so much for the care to edit the entry, @sammyhori!

**Comment by sammyhori** [comment]
That's okay, thank you for the entry :)

**Pull request merged**
