### PR TITLE
Add tinyhttp to the TypeScript section

### PR DESCRIPTION
**Pull request by talentlessguy**
Please complete the following checklist if your PR is adding new link to the list:

- [x] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [x] This PR does not introduce duplicates to the list
- [x] The link is added at the bottom of the list category
- [x] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label

tinyhttp has 400+ stars, 8 open "good first issue" issues and 11 existing contributors. I think it's enough to qualify for this criteria?

- [x] The link I add follows the suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

**project description**

tinyhttp is a modern Express-like web framework written in TypeScript and compiled to native ESM, that uses a bare minimum amount of dependencies trying to avoid legacy hell.

**stats**

stars - 900+
coverage - 92%+
contributors - 26+
8 open "good first issue" issues

I hope that I followed all of the requirements so looking forward for this PR to be checked :)

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @talentlessguy 

Thanks for the PR, would you be able to fix the link format?

Thanks!

**Comment by talentlessguy** [comment]
@MunGell I'm not sure what's the problem is. Doesn't the link follow the format?

```markdown
- [tinyhttp](https://github.com/talentlessguy/tinyhttp/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) _(label: good first issue)_ <br> A 0-legacy, tiny & fast web framework as a replacement of Express.
```

- [tinyhttp](https://github.com/talentlessguy/tinyhttp/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) _(label: good first issue)_ <br> A 0-legacy, tiny & fast web framework as a replacement of Express.

**Comment by MunGell** [comment]
Fixed formatting in 566f19b

**Comment by talentlessguy** [comment]
thanks for merging! 😊

**Pull request merged**
