### PR TITLE
Add OrgManager

### PR DESCRIPTION
**Pull request by m1guelpf**
Adds OrgManager

### CODE REVIEW

**Comment by m1guelpf** [comment]
@MunGell Any updates?

**Comment by MunGell** [comment]
Hi @m1guelpf 

Thanks for your PR! One of the criteria to be accepted to this list is active community around the project.

Your project is quite young and has no beginner-friendly issues opened.
I will park this PR until your project get bigger community that will be able to help beginners.

Thanks

**Comment by m1guelpf** [comment]
@MunGell Updates?

**Comment by MunGell** [comment]
Hey @m1guelpf 

I am merging this PR now, however there is only one beginner-friendly issue and still you are the only contributor to the repository.

**Pull request merged**
