### PR TITLE
53 # ZeroCode API Testing - REST, KAFKA, SOAP and DB API testing lib

### PR DESCRIPTION
**Pull request by authorjapps**

### CODE REVIEW

**Comment by authorjapps** [comment]
Hello Guys, How to merge this PR? Is there any process to follow to get this approved?

**Comment by MunGell** [comment]
Hey @authorjapps 

I've written contributing guidelines for this repository - please have a look there.
In general - your project is too new and has not formed strong community around it to support new contributors (one of the criteria in the guidelines). I will leave this PR open for some time until you will get a wider community support. Or you can close it and create a new one when you will get more people involved

**Comment by MunGell** [comment]
Hi @authorjapps 

A year passed since you opened this PR and it looks like your repository is active and project is moving forward - great job!

I see that you have `good first issue` label as well.

Could you please clarify which one is used to label issues for beginners in contribution to open source?

**Comment by authorjapps** [comment]
Hello @MunGell ,
Thanks for coming back on this.
Label "**good first issu**e" for beginners and "**help wanted**" is general for all not necessarily for beginners.

**Comment by MunGell** [comment]
@authorjapps I understand the difference between "help wanted" and "good first issue".
However, in this PR you are suggesting "first-time-high-flight" label.

Could you clarify how is it used and what is the difference between "first-time-high-flight" and "good first issue"?

**Comment by authorjapps** [comment]
> Could you clarify how is it used and what is the difference between "first-time-high-flight" and "good first issue"?

Understood, `"first-time-high-flight"` is creating confusion. I have got rid of that label now and updated with "good first use" label and link.

**Pull request merged**
