### PR TITLE
Add SymPy to Python projects

### PR DESCRIPTION
**Pull request by friyaz**
SymPy is a Python library for symbolic computations.

Please complete the following checklist if your PR is adding new link to the list:

- [x] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [x] This PR does not introduce duplicates to the list
- [x] The link is added at the bottom of the list category
- [x] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [x] The link I add follows the suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @friyaz 

Thanks for the PR, do you know if [good first issue](https://github.com/sympy/sympy/labels/good%20first%20issue) is a better label to be included in this list? Is it possible to contact one of the SymPy maintainers to clarify the difference?

**Comment by friyaz** [comment]
Hi @MunGell!

The good first issue is used scarcely by maintainers. Most easy issues in SymPy have the label `Easy to Fix`. Please see https://github.com/sympy/sympy/issues/13465 for more details.

**Comment by friyaz** [comment]
Also, you can have a look at Jason's comment on https://github.com/sympy/sympy/issues/13520.

**Comment by MunGell** [comment]
Great, thanks for these links, they explain it well!

**Pull request merged**
