### PR TITLE
Added some projects in Swift language

### PR DESCRIPTION
**Pull request by cherryWood55**
I have enumerated a couple of projects in Swift language with their labels which are easy to pick for a beginner.
The above addresses issue #428.
Please review.
Thanks!

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @cherryWood55 

Thanks for the PR. Could you please review the format and contents of these projects?
Some of them have no appropriate label.

**Comment by cherryWood55** [comment]
Sure. I will do.

**Comment by cherryWood55** [comment]
@MunGell please review the above changes.

**Comment by MunGell** [comment]
Links format is still broken, closing this PR.
Please open new one when ready

**Pull request closed without merging**
