### PR TITLE
Add node-starter

### PR DESCRIPTION
**Pull request by jinnatul**
Adding https://github.com/jinnatul/node-starter.

### CODE REVIEW

**Comment by jinnatul** [comment]
Hello @MunGell, Please check my pr when you are available

**Comment by jinnatul** [comment]
Hello @MunGell and @c-mart, Please check my pr when you are available

**Review by sammyhori — COMMENTED** [review]
No issues in repo

**Comment by sammyhori** [comment]
As this pull request goes against the contributing guideline of

> Ensure the contributed repository is actively maintained, has a supportive community, and _**issues with appropriate labels**_.

I am closing this pull request. Feel free to reopen this PR if some issues with appropriate labels are made.

**Comment by jinnatul** [comment]
Hello @sammyhori , reopened another [pr](https://github.com/MunGell/awesome-for-beginners/pull/1476). Please let me know if you need to update something. Thanks

**Pull request closed without merging**
