### PR TITLE
Added opsdroid

### PR DESCRIPTION
**Pull request by jacobtomlinson**
We add issues for beginners and are happy to mentor new contributors through their first open source experiences.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
@vvscode ah I totally missed that! Fixed now!

**Comment by MunGell** [comment]
Hi @jacobtomlinson 

Sorry for the wait, do you know what is the difference between "beginner" and "good first issue" labels in this repository?

**Comment by jacobtomlinson** [comment]
No worries. Would be great to get this moved along.

`good first issue` is exactly that, issues specifically aimed at first time contributors. `beginner` is the difficults of an issue, there are also `intermediate` and `advanced` labels.

**Comment by MunGell** [comment]
@jacobtomlinson would `good first issue` be a better choice for this list? 

As I understand it, `good first issue` is a subset of `beginner` issues, so every `good first issue` is also a `beginner`, but not every `beginner` issue is good for first-time contributors.

Since this repository is a starting point for first-time contributors to find your repository, it sounds like `good first issue` is a better option for them.

What do you think?

**Comment by jacobtomlinson** [comment]
Sure happy with that. 

We intentionally make the `good first issue` very well described for newbies. Often we put more effort into writing the issue than it would take to implement the change.

The `beginner` issues are less described and aimed at people who want easy issues but have a bit of entry level knowledge.

I went with `beginner` because this repo is called `awesome-for-beginners`. However if you think we should only be targeting first timers I'm happy with that too.

**Comment by MunGell** [comment]
Ok, I see.

Then I will leave the decision on which label to point new contributors to to you.
I believe this issue might give a little insight: https://github.com/MunGell/awesome-for-beginners/issues/215

If all ok, please resolve the conflicts and I will merge this PR

Thanks!

**Comment by jacobtomlinson** [comment]
Fixed conflict and went for `good first issue`.

**Comment by MunGell** [comment]
Perfect, thanks!

**Pull request merged**
