### PR TITLE
Changed C++ Section to Alphabetic Order

### PR DESCRIPTION
**Pull request by polilluminato**
I Changed the C++ Section to Alphabetic Order because I think that It's easier to read.

### CODE REVIEW

**Comment by polilluminato** [comment]
I merged two of my branches in this single pull request. If this is not allowed I can close this pull request and make a single one only for the last commit that's related to the C++ section.

**Comment by polilluminato** [comment]
I think it's relevant but I haven't received an answer yet.

**Comment by MunGell** [comment]
Hi @polilluminato 

Would you mind rebasing this PR so that there will be no changes from your .NET PR that I've just merged?

**Comment by polilluminato** [comment]
> Hi @polilluminato
> 
> Would you mind rebasing this PR so that there will be no changes from your .NET PR that I've just merged?

Yeah, I'll rebase my repo and I'll create single pull request for each section.

**Pull request closed without merging**
