### PR TITLE
add first contributions

### PR DESCRIPTION
**Pull request by Roshanjossey**
A sandbox project to help beginners learn the process of contributing to projects on GitHub with a hands-on tutorial

### CODE REVIEW

**Comment by sammyhori** [comment]
I like this, but am wondering if, due to its special function, we could perhaps integrate it more specifically, for those who have never contributed to a repository before.

Perhaps we could add something to `README-template.j2` (in the `.github` directory).

**Comment by sammyhori** [comment]
Perhaps something like #1538?

Let me know your thoughts :)

**Comment by Roshanjossey** [comment]
I like the idea. I get that it could help a lot more people there. Also, you described it better too 🙌

**Comment by sammyhori** [comment]
> I like the idea. I get that it could help a lot more people there. Also, you described it better too 🙌

Cool 👍, thanks for the entry suggestions, I'll close this PR and merge the other.

**Comment by sammyhori** [comment]
Closed in favour of #1538

**Pull request closed without merging**
