### PR TITLE
Update Roc link

### PR DESCRIPTION
**Pull request by gavv**
"Roc" was renamed to "Roc Toolkit", this PR updates the name and link.

### CODE REVIEW

**Comment by gavv** [comment]
.

**Comment by gavv** [comment]
.

**Comment by gavv** [comment]
.

**Comment by gavv** [comment]
.

**Comment by gavv** [comment]
Damn.

**Comment by MunGell** [comment]
Hi @gavv 

Sorry fro the bot, it is designed to help me deal with irrelevant PRs, especially during Hacktoberfest.

Thanks for the update!

**Comment by gavv** [comment]
@MunGell Thanks.

**Pull request merged**
