### PR TITLE
Fix label for cockroachDB

### PR DESCRIPTION
**Pull request by mstruebing**

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @mstruebing 

Thanks for the PR, I was just looking at cockroachDB repository labels and found several ones that might be suitable for first-time contributors:

* [E-starter](https://github.com/cockroachdb/cockroach/labels/E-starter) *(in this PR)* – "Might be suitable for a starter project for new employees or team members."
* [E-easy](https://github.com/cockroachdb/cockroach/labels/E-easy) – "Easy issue to tackle, requires little or no CockroachDB experience"
* [good first issue](https://github.com/cockroachdb/cockroach/labels/good%20first%20issue)

To me it looks like `good first issue` is the most appropriate label for this list, but we can double check with @jordanlewis

Thanks!

**Comment by jordanlewis** [comment]
Hi @MunGell,

`E-starter` is really reserved for internal usage for onboarding employees.

`E-easy` is a good label. `good first issue` is also a good label. Frankly, we left `good first issue` because we thought it was "specially ordained" by GitHub to be a starter label. In an ideal world, since we have such a large repo and a lot of labels, we'd stick to the `E-easy` label for this kind of thing, to keep the `E-` (experience level) prefix consistent.

**Comment by jordanlewis** [comment]
By the way, thank you for doing this work! We really appreciate it, as do people trying to break into open source. Keep it up!

**Comment by mstruebing** [comment]
I'm using the `E-easy` label now.

**Comment by MunGell** [comment]
Thanks @mstruebing @jordanlewis

**Pull request merged**
