### PR TITLE
Add tool Harmony https://github.com/harmonydata/harmony

### PR DESCRIPTION
**Pull request by woodthom2**
Added Harmony, a tool for psychologists and social scientists to analyse data.

Psychologists and social scientists often have to match items in different questionnaires, such as "I often feel anxious" and "Feeling nervous, anxious or afraid".
This is called harmonisation.
Harmonisation is a time consuming and subjective process.
Going through long PDFs of questionnaires and putting the questions into Excel is no fun.
Enter [Harmony](https://harmonydata.ac.uk/app), a tool that uses [natural language processing](https://github.com/harmonydata/harmony/blob/main/naturallanguageprocessing.com) and generative AI models to help researchers harmonise questionnaire items, even in different languages.

### CODE REVIEW

**Review by sammyhori — COMMENTED** [review]
Current has no "Good First Issue" issues

**Comment by sammyhori** [comment]
As this pull request goes against the contributing guideline of:

>   Ensure the contributed repository is actively maintained, has a supportive community, and **_issues with appropriate labels_**.

I am closing this pull request. Feel free to reopen this PR if some issues with appropriate labels are made.

**Comment by sammyhori** [comment]
Hi @woodthom2, thanks for the update, I'm happy to add your repository to the list now 👍.

Regarding your LLM competition, would you say it's beginner friendly? What kind of improvements are you looking for?
I would be interested in adding a competitions section, but I'm not sure your competition is necessarily beginner friendly enough for the people visiting this list (people looking for simple programming problems). Nevertheless, I am tempted.

**Comment by woodthom2** [comment]
Thanks so much @sammyhori ! I think the competition is "intermediate friendly". A person with familiarity with Jupyter notebooks can run it, and we provide example notebooks so you can get started, but definitely I would not say it's for beginners. However, feel free to give it a go - or you could maybe add a footnote to Harmony's entry in your directory to say "if you're up for a challenge, try this competition"? Whatever fits best with your project!

**Comment by sammyhori** [comment]
The footnote idea sounds good!
The `data.json` should support markdown formatting in the description, I'll give that a go.

**Comment by sammyhori** [comment]
All done! See your Harmony entry under the [Javascript section](https://harmonydata.ac.uk/doxa/).

**Comment by woodthom2** [comment]
Thanks so much!

**Pull request merged**
