### PR TITLE
Added the PR friendly Julians

### PR DESCRIPTION
**Pull request by abhi18av**
Low hanging fruits on Julia lang

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @abhi18av 

Thanks for contribution!

We can only accept repositories and links to labels that are dedicated to beginners.
Labels like `documentation` etc. are not dedicated to beginners and issues with these labels are not really beginner-friendly (they have very limited description of the problem).

Could you please update your PR, remove irrelevant links and fix formatting?

**Comment by abhi18av** [comment]
Hey @MunGell , is the latest commit https://github.com/abhi18av/awesome-for-beginners/commit/63e125d23f1493ce8f304c0b85c7c332ff777391  an improvement?

Let me know :)

**Comment by MunGell** [comment]
I can merge this PR and update it afterwards if you don't mind.

**Comment by abhi18av** [comment]
Hmm, sure)

**Comment by MunGell** [comment]
Thanks! :)

**Comment by abhi18av** [comment]
No issues, it's a really awesome project! Hope this helps people get started with Open Source and collaboration faster)

**Comment by MunGell** [comment]
Thanks! Just did small formatting changes. Julia's labels are not too straightforward :)

Reference for future, when they will figure them out:

- https://groups.google.com/forum/#!topic/julia-users/ewyVO4HIm4Y
- https://groups.google.com/forum/#!topic/julia-dev/1IWQcXNsilk

**Pull request merged**
