### PR TITLE
Update HMPL data

### PR DESCRIPTION
**Pull request by aanthonymax**
The repository has been moved, information has been updated.

### CODE REVIEW

**Review by sammyhori — COMMENTED** [review]
Hi, thanks for the contribution!

Unfortunately this repository really no longer meets the requirements of the list as it doesn't have any issues marked _good first issue_. I'm also a little worried at the small size of this repo.

Therefore, unless the requirements are met, I suggest that this entry is removed instead.

**Comment by aanthonymax** [comment]
@sammyhori Since I was moving the repository, a lot was removed, which is why it looks like this now.

**Comment by sammyhori** [comment]
Oh okay, that makes sense. Checking the web archive from the [13th of September](https://web.archive.org/web/20240913222226/https://github.com/hmpl-lang/hmpl), it shows the repository had 89 commits. It doesn't show any issues but that could easily be an problem with the archival/snapshotting method, especially given [I approved the repository last month](https://github.com/MunGell/awesome-for-beginners/pull/1472) stating that there were some good first issues.

**Comment by sammyhori** [comment]
Does GitHub not let you change organisation names? That is a pain

**Comment by aanthonymax** [comment]
@sammyhori You can look at the commits here - https://github.com/Nikshinde7/hmpl. There are people's work left there. I just don't understand, like, when you delete an organization completely, all the repositories go to the first fork made, which is of course strange. I just didn't want to associate that account with the repository anymore, so i deleted it, but I will never do that again in my life, because it was easier to transfer it to another account, rather than delete it. My mistake.

**Comment by sammyhori** [comment]
I see that, that is strange behaviour from GitHub.

Thanks for adding some good first issues, I'm happy to merge this change.

**Review by sammyhori — APPROVED** [review]
Has some appropriately labelled issues.

Repo doesn't have many commits but that's because its been copied from another repository as seen in the discussion.

**Pull request merged**
