### PR TITLE
Add vegeta-server under Go

### PR DESCRIPTION
**Pull request by nitishm**
Vegeta servier is a A RESTful API server for vegeta, a load testing tool written in Go.

### CODE REVIEW

**Comment by nitishm** [comment]
> I see that your label is `Difficulty: Introductory`

Thanks. Fixed it.

**Comment by MunGell** [comment]
This repository also has "good first issue" and "up-for-grabs" labels.
Could you please clarify which one is used for new contributors?

**Comment by nitishm** [comment]
Good first issue would be the right one

**Comment by MunGell** [comment]
Will you be able to update this PR then?

**Pull request closed without merging**
