### PR TITLE
Updating FreeCodeCamp lable to currently used first timer tag

### PR DESCRIPTION
**Pull request by mmmvdb**
I was running around checking your awesome list, and noticed that FreeCodeCamp didn't have any issues listed.  However I could go look at the full issue list and see some first timer issues.

It turns out the link and tag this list was looking for was using "first timers welcome" but the FreeCodeCamp repo apparently has changed to "first timers only".

Rather than trying to send in an issue, I figured I'd just fix your list and try my first pull request.  Let me know if I've done anything wrong with this, or didn't follow the process below (I figured I'd get some passes since this is a existing link, and not a new link, so I maintained the current list order etc.)

Please complete the following checklist if your PR is adding new link to the list:

- [X] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [X] This PR does not introduce duplicates to the list
- [ ] The link is added at the bottom of the list category
- [X] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [X] The link I add follows the suggested pattern[...]

Old Label:
image

New Label:
image

### CODE REVIEW

**Comment by Mrskillful** [comment]
Great Catch! There doesn't seem to be any conflicts. 

Not sure how to go about the 3rd checkbox, because all you did was edit a current link, but from what I'm seeing everything looks pretty good. 

Hopefully, it gets pushed with no problems.

**Comment by thamara** [comment]
> Hopefully, it gets pushed with no problems.

If the stale bot doesn't catch you...

**Comment by Ieahleen** [comment]
what is blocking it... not being reviewed and merged, it seems

@mmmvdb want to try again?

**Comment by MunGell** [comment]
Hi @mmmvdb 

Thanks for the fix and sorry for the delay in response!

**Pull request merged**
