### PR TITLE
add tldr pages in a new "Markdown" category

### PR DESCRIPTION
**Pull request by yasharmaster**
Created a new category called "Markdown" and added a project "tldr-pages" under it.

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @yasharmaster 

I can't find "beginner" labels in the tldr repository. Each repository in the list has to have a dedicated issue label for beginners.

**Comment by yasharmaster** [comment]
@MunGell Sorry, I thought we have to put the label as we see fit. I shall update the PR. The label on the issues is actually "new command".

**Comment by MunGell** [comment]
From what I understand, `new command` is a version of `new feature` issue label in this repository. There are a lot of issues with this label there, but many of them are barely beginner-friendly.

This repository contains a list of projects that have issues dedicated to beginners. These issues supposed to be well explained so new joiners would be able to understand what is needed to be done.

Unfortunately, I cannot merge this PR.
Please refer to @kentcdodds's the original article for an example of beginner-friendly issue.

**Comment by MunGell** [comment]
Thank you!

**Pull request closed without merging**
