### PR TITLE
adding Habitica to the list

### PR DESCRIPTION
**Pull request by Ieahleen**
Please complete the following checklist if your PR is adding new link to the list:

- [x] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [x] This PR does not introduce duplicates to the list
- [x] The link is added at the bottom of the list category
- [x] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [x] The link I add follows the suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

### CODE REVIEW

**Comment by Ieahleen** [comment]
waiting for review

**Comment by Ieahleen** [comment]
just waiting for review

Il giorno lun 10 ago 2020 alle 17:52 stale[bot] <notifications@github.com>
ha scritto:

**Comment by MunGell** [comment]
Hi @Ieahleen 

Thanks for the PR, could you please update the URL to https://github.com/HabitRPG/habitica/labels/good%20first%20issue ?

**Comment by MunGell** [comment]
Still relevant

**Comment by Ieahleen** [comment]
I will do it as soon as I can, I haven't had the time to sit at the
computer lately

Il giorno lun 24 ago 2020 alle 10:33 Shmavon Gazanchyan <
notifications@github.com> ha scritto:

**Comment by MunGell** [comment]
No worries, just keeping stalebot away from this PR

**Pull request merged**
