### PR TITLE
Update VS code link

### PR DESCRIPTION
**Pull request by RetroCraft**
Label: good first issue and label:help wanted are now used instead on the vs code repository

### CODE REVIEW

**Comment by waldyrious** [comment]
@RetroCraft if you use `+` instead of `%20` as word separator in the url, it still works, but the markdown source is more readable :)

**Comment by waldyrious** [comment]
@RetroCraft I'm sorry -- either GitHub's renderer has changed since I last checked, or I mixed things up in my head: the `+` link doesn't work after all. I vaguely recall recently interacting with @kivikakk on this issue, who probably can offer useful insight, but I may be mistaken.

**Comment by RetroCraft** [comment]
Commit removed.

**Comment by kivikakk** [comment]
This might work in some instances where `+` and space are equivalent, but this particular URL isn't one of them; this usually _will_ work after a `?` (i.e. as part of a query string), where they are equiv.

**Comment by MunGell** [comment]
Thanks!

**Pull request merged**
