### PR TITLE
Update the project name to Trino

### PR DESCRIPTION
**Pull request by findepi**
https://github.com/prestosql/presto/ redirects
https://github.com/trinodb/trino

Please complete the following checklist if your PR is adding new link to the list:

- [x] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [x] This PR does not introduce duplicates to the list
- ~The link is added at the bottom of the list category~ (it's an update)
- [x] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [x] The link I add follows the suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

### CODE REVIEW

**Comment by findepi** [comment]
@MunGell this is follow up to #657

**Comment by findepi** [comment]
@MunGell can you please take a look?

**Comment by findepi** [comment]
@MunGell merge please when you have time. This updates a link after the project has been moved.

**Comment by MunGell** [comment]
Hi @findepi 

I am really sorry for the wait, thank you for keeping link in this list up to date!

**Pull request merged**
