### PR TITLE
Add Git Started

### PR DESCRIPTION
**Pull request by jwu910**
Would like to add a JavaScript project to the readme. Thanks

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @jwu910 

Sorry for the delay, I gave this project half a year to see if it will fit to the description of a project that can be added to the list.
Unfortunately, it does not look like this repository has much activity and PRs are open since March (ironic that I mention that...). So I am closing this PR.

**Comment by jwu910** [comment]
Right on, we're prepping for another release this month, and are opening more easy to tackle issues.

What is your threshold for Activities and PRs that make it to your lists?

**Comment by jwu910** [comment]
Right on @MunGell this project sorta fell through after we got it started. Been focusing on some other tools at the moment. I appreciate the reviews

**Comment by MunGell** [comment]
No worries, and thanks for coming back. This is one of the reasons I don't accept very new projects...
Feel free to create PRs for your new projects when you get a community around them that will not let project die prematurely!

**Pull request closed without merging**
