### PR TITLE
added pylearn2 in python projects

### PR DESCRIPTION
**Pull request by VishvajitP**

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @VishvajitP 

Thanks for contribution.
The repository you are adding has no label `easy` in it. Instead, they have label [For beginners](https://github.com/lisa-lab/pylearn2/labels/For%20beginners), which suits this repository's purpose.

Please update your PR (see how other links are formatted) according to contributing guidelines.
It would also be nice if you could remove a redundant new line under the link.

**Comment by VishvajitP** [comment]
@MunGell : Can you please review the PR and merger if everything is alright ?

**Comment by MunGell** [comment]
Hi @VishvajitP 

As noted in the message above, please update your PR with correct link to `For beginners` label

**Comment by VishvajitP** [comment]
@MunGell Have updated the correct link. Please check.

**Comment by reed9999** [comment]
I'm a little surprised pylearn2 was included, since the README starts out "This project does not have any current developer" (and has been that way since before it was added to Awesome for Beginners). Is a current developer not a requirement to add a project?

**Pull request merged**
