### PR TITLE
Added tree-sitter-legesher-python project to Python section

### PR DESCRIPTION
**Pull request by wescran**
Added `tree-sitter-legesher-python` project to Python section. Text editor also removed trailing whitespace from another submission. [Link for maintainer confirmation on label](https://github.com/legesher/tree-sitter-legesher-python/issues/12#issue-498907502)

Please complete the following checklist if your PR is adding new link to the list:

- [x] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [x] This PR does not introduce duplicates to the list
- [x] The link is added at the bottom of the list category
- [x] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [x] The link I add follows suggested pattern:

```
- [Repository Name](link-to-repository-label) _(label: beginner-friendly-label-in-the-repository)_ <br> Description
```

Example link formatting:

```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly projects.
```

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @wescran 

Would you mind updating the link to be in line with the guidelines? Please see the checklist

Thnaks

**Comment by MunGell** [comment]
Thanks!

**Comment by wescran** [comment]
Oops, sorry about that! I was following this format from the [`CONTRIBUTING.MD`](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md) 
>Use the following format: - `[Repository Name](link-to-repository) _(beginner-friendly-label-in-the-repository)_ <br> Description`

It didn't have the label name in the link so I just linked the repo. I must have overlooked the link in the checklist.

**Comment by MunGell** [comment]
No worries, looks like contributing guidelines need to be updated :)

**Comment by wescran** [comment]
@MunGell I can do that if you would like, if not no worries :)

**Comment by MunGell** [comment]
That would be great, thank you!

**Pull request merged**
