### PR TITLE
new Go tool

### PR DESCRIPTION
**Pull request by lucky-sideburn**
Added Congruit!

### CODE REVIEW

**Comment by lucky-sideburn** [comment]
The configuration management tool that loves Bash

Simple, lightweight and fully customizable by you :)

**Comment by MunGell** [comment]
Hi @lucky-sideburn 

Unfortunately, I cannot accept your PR as it does not follow contribution guidelines.

In particular "Contributed repository must be maintained, have active community to be able to help newcomers and have issues with appropriate label".

The repository you are contributing does not have issues and community as it is relatively new.

Thanks

**Comment by lucky-sideburn** [comment]
Hi MunGell!

thank you and sorry for my mistake :)

bye!

**Comment by MunGell** [comment]
No worries!
Happy to accept your repository when you will get a community around it and beginner-friendly issues.

**Pull request closed without merging**
